package com.hkl.chuanuc.entity;
// Generated Aug 25, 2019 6:12:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "shopify")
public class Address implements java.io.Serializable {

	private AddressId id;
	private User user;
	private byte city;
	private short provincal;
	private short ward;
	private String address;
	private String phone;
	private boolean default_;
	private Date updated;

	public Address() {
	}

	public Address(AddressId id, User user, byte city, short provincal, short ward, String address, String phone,
			boolean default_, Date updated) {
		this.id = id;
		this.user = user;
		this.city = city;
		this.provincal = provincal;
		this.ward = ward;
		this.address = address;
		this.phone = phone;
		this.default_ = default_;
		this.updated = updated;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "city", nullable = false)
	public byte getCity() {
		return this.city;
	}

	public void setCity(byte city) {
		this.city = city;
	}

	@Column(name = "provincal", nullable = false)
	public short getProvincal() {
		return this.provincal;
	}

	public void setProvincal(short provincal) {
		this.provincal = provincal;
	}

	@Column(name = "ward", nullable = false)
	public short getWard() {
		return this.ward;
	}

	public void setWard(short ward) {
		this.ward = ward;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "default", nullable = false)
	public boolean isDefault_() {
		return this.default_;
	}

	public void setDefault_(boolean default_) {
		this.default_ = default_;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
