package com.hkl.chuanuc.entity;
// Generated Aug 25, 2019 6:12:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DebtLog generated by hbm2java
 */
@Entity
@Table(name = "debt_log", catalog = "shopify")
public class DebtLog implements java.io.Serializable {

	private DebtLogId id;
	private Order order;
	private byte type;
	private Date created;
	private long amount;
	private long debt;

	public DebtLog() {
	}

	public DebtLog(DebtLogId id, Order order, byte type, Date created, long amount, long debt) {
		this.id = id;
		this.order = order;
		this.type = type;
		this.created = created;
		this.amount = amount;
		this.debt = debt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)) })
	public DebtLogId getId() {
		return this.id;
	}

	public void setId(DebtLogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "type", nullable = false)
	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "amount", nullable = false)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "debt", nullable = false)
	public long getDebt() {
		return this.debt;
	}

	public void setDebt(long debt) {
		this.debt = debt;
	}

}
