package com.hkl.chuanuc.entity;
// Generated Aug 25, 2019 6:12:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductPack generated by hbm2java
 */
@Entity
@Table(name = "product_pack", catalog = "shopify", uniqueConstraints = @UniqueConstraint(columnNames = "quantity"))
public class ProductPack implements java.io.Serializable {

	private Byte id;
	private short quantity;
	private String description;
	private boolean available;
	private Set<ProductPackPriceInfo> productPackPriceInfos = new HashSet<ProductPackPriceInfo>(0);

	public ProductPack() {
	}

	public ProductPack(short quantity, String description, boolean available) {
		this.quantity = quantity;
		this.description = description;
		this.available = available;
	}

	public ProductPack(short quantity, String description, boolean available,
			Set<ProductPackPriceInfo> productPackPriceInfos) {
		this.quantity = quantity;
		this.description = description;
		this.available = available;
		this.productPackPriceInfos = productPackPriceInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	@Column(name = "quantity", unique = true, nullable = false)
	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "available", nullable = false)
	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productPack")
	public Set<ProductPackPriceInfo> getProductPackPriceInfos() {
		return this.productPackPriceInfos;
	}

	public void setProductPackPriceInfos(Set<ProductPackPriceInfo> productPackPriceInfos) {
		this.productPackPriceInfos = productPackPriceInfos;
	}

}
