package com.hkl.chuanuc.entity;
// Generated Aug 25, 2019 6:12:29 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductPackPriceInfo generated by hbm2java
 */
@Entity
@Table(name = "product_pack_price_info", catalog = "shopify")
public class ProductPackPriceInfo implements java.io.Serializable {

	private ProductPackPriceInfoId id;
	private Product product;
	private ProductPack productPack;
	private long price;

	public ProductPackPriceInfo() {
	}

	public ProductPackPriceInfo(ProductPackPriceInfoId id, Product product, ProductPack productPack, long price) {
		this.id = id;
		this.product = product;
		this.productPack = productPack;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "productPackId", column = @Column(name = "product_pack_id", nullable = false)) })
	public ProductPackPriceInfoId getId() {
		return this.id;
	}

	public void setId(ProductPackPriceInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_pack_id", nullable = false, insertable = false, updatable = false)
	public ProductPack getProductPack() {
		return this.productPack;
	}

	public void setProductPack(ProductPack productPack) {
		this.productPack = productPack;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

}
