package com.hkl.chuanuc.entity;
// Generated Aug 25, 2019 6:12:29 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "shopify")
public class Product implements java.io.Serializable {

	private ProductId id;
	private ProductBrand productBrand;
	private ProductCategory productCategory;
	private String name;
	private String code;
	private long basePrice;
	private int instock;
	private int weight;
	private String description;
	private String note;
	private String image;
	private Set<ProductPackPriceInfo> productPackPriceInfos = new HashSet<ProductPackPriceInfo>(0);
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Product() {
	}

	public Product(ProductId id, ProductBrand productBrand, ProductCategory productCategory, String name, String code,
			long basePrice, int instock, int weight, String description, String note, String image) {
		this.id = id;
		this.productBrand = productBrand;
		this.productCategory = productCategory;
		this.name = name;
		this.code = code;
		this.basePrice = basePrice;
		this.instock = instock;
		this.weight = weight;
		this.description = description;
		this.note = note;
		this.image = image;
	}

	public Product(ProductId id, ProductBrand productBrand, ProductCategory productCategory, String name, String code,
			long basePrice, int instock, int weight, String description, String note, String image,
			Set<ProductPackPriceInfo> productPackPriceInfos, Set<OrderDetail> orderDetails) {
		this.id = id;
		this.productBrand = productBrand;
		this.productCategory = productCategory;
		this.name = name;
		this.code = code;
		this.basePrice = basePrice;
		this.instock = instock;
		this.weight = weight;
		this.description = description;
		this.note = note;
		this.image = image;
		this.productPackPriceInfos = productPackPriceInfos;
		this.orderDetails = orderDetails;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "productCategoryId", column = @Column(name = "product_category_id", nullable = false)),
			@AttributeOverride(name = "productBrandId", column = @Column(name = "product_brand_id", nullable = false)) })
	public ProductId getId() {
		return this.id;
	}

	public void setId(ProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_brand_id", nullable = false, insertable = false, updatable = false)
	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_category_id", nullable = false, insertable = false, updatable = false)
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "name", nullable = false, length = 125)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "base_price", nullable = false)
	public long getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(long basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "instock", nullable = false)
	public int getInstock() {
		return this.instock;
	}

	public void setInstock(int instock) {
		this.instock = instock;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "note", nullable = false, length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "image", nullable = false, length = 16)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductPackPriceInfo> getProductPackPriceInfos() {
		return this.productPackPriceInfos;
	}

	public void setProductPackPriceInfos(Set<ProductPackPriceInfo> productPackPriceInfos) {
		this.productPackPriceInfos = productPackPriceInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
